### ISSUE TITLE
Pressing   ctrl+y+,   doesn't work

### ISSUE THREAD

**Issue by DMK2013** [mattn/emmet-vim#148]
I installed everything according to the instructions. I put the emmet folder under bundle. 
When I tried sample as

> > Press "Insert"
> > Type In "html:5"
> > Press "ctrl"+"y"+","

But nothing happens. I tried other emmet shortcuts as well but none of them works.

**Comment by jwhitley** [comment]
Kudos to @jtmkrueger, that's also my issue. In my case, I've got [some insert-mode specific autocmd trickery](https://github.com/jwhitley/vimrc/blob/master/.vimrc#L114) that switches `timeoutlen` to 0 only in insert-mode.  That utterly defeats emmet's binding approach, since it's impossible to enter the follow-on character after a `<C-y>` mapping (e.g. `<C-y>,` to expand an emmet abbreviation).

I may see if I can do something horrible like create a wrapper prefix mapping (say, `<C-e>`) that resets `timeoutlen` to a non-zero value, then restores it when the emmet command is complete?  If you hear evil cackling from miles away, you'll know I've succeeded.  :smiling_imp:

**Comment by jwhitley** [comment]
Followup: AFAICT, it's impossible to create a Vim wrapper function that executes just the prefix of an existing keybinding, e.g. as a kind of passthru: `<c-e>{blah} => <c-y>{blah}`.  This is because :normal bails if its command argument is incomplete, just as if `<esc>` or `<C-c>` were pressed.

However, as a tentative workaround, `set timeoutlen=100` (vs zero) in insert mode seems to provide a happy medium where the keybinding works but returning to normal mode is still snappy.

**Comment by mattn** [comment]
I don't understand why you need the trick of fast esc.

**Comment by mattn** [comment]
@jwhitley I suggest https://github.com/kana/vim-arpeggio to you. :)

**Comment by anthonybrown** [comment]
@jtmkrueger thanks, commenting out the `set timeoutlen=0` fixed my issues. emmet is working in both vim and macvim, both compiled from brew.

**Comment by wsdjeg** [comment]
your plugin is very usefull for me,thank you for you work

**Comment by iolloyd** [comment]
Increasing timeoutlen worked for me.

**Comment by JDoeW** [comment]
same problem, I set let g:user_emmet_leader_key='<C-Z>,' not let g:user_emmet_leader_key='<C-Z>'

**Comment by jngilman** [comment]
mattn, thank you for the plug-in.

I had the same problem.

I eventually solved it by exiting and quitting terminal on my mac and restarting.

**Comment by shengnoyi** [comment]
1. Try to type 'html:5' in insert mode.
2. Back to normal mode.
3. press 'Ctrl + Y + ,'
if it works, it means the plugin can work but you need to set emmet-vim activated into insert mode.

**Comment by mattn** [comment]
you can expand with emmet on insert mode too.

**Comment by grossshen** [comment]
I can't use emmet on insert model, but can in normal model. I user CentosOs7 and vim7

**Comment by gwanghyeongim** [comment]
If you installed emmet with vim-plug and somehow emmet is not working, try installing with Vundle. I soloved the issue with this.

**Comment by speedy1812** [comment]
If your are installing with Vim-Plug, don't forget to run `:PlugInstall`, or whatever the analogous command is for your plugin manager. It may seem obvious, but I forgot to do so and was pulling my hair out for a while trying to figure out why the trigger key wasn't working. 🤦‍♂️

**Comment by kez-sys** [comment]
I was having the same problem _let g:user_emmet_leader_key_ wasnt changing my leader key but all i had to do is rerun terminal vim and the new assigned leader key works.

**Comment by branquito** [comment]
> I've found that `timeoutlen=0` was killing this for me. I'm an avid `<C-[>` to escape user, and setting this made some things work a little quicker (mainly my status line color function). Commenting this line out of my `.vimrc` immediately returned the correct `<C-y>,` functionality.

Oh God, how frustrated I was because it doesn't work but just in insert mode, and this was the culprit. Many thanks for this one!

**Comment by danushk** [comment]
in vimrc set timeoutlen=250, breaks <C-y >+<,> Emmet trigger

even reloading vimrc with :source $MYVIMRC<CR> does not fix it - you have to :qa and run vim again to fix this.

**Comment by ranelpadon** [comment]
@jtmkrueger Thanks a lot for your tip!

@mattn Thanks for this excellent plugin. Just wondering if we could include a note/warning in the docs/README regarding the `timeoutlen=0`, or any value that is too low for the `<C-Y>,` key sequences? This caused me few hours of troubleshooting which just led to nowhere, which could be easily avoided if possible conflicts with `timeoutlen` setting was emphasized in the docs. 

This issue was filed on Sep 2013 (7 years ago), but still pester lots of people up to now based on the comments here. An improved README could easily prevent this. :)

**Comment by i4ever** [comment]
> Did you try below?
> 
> 1. Press `CTRL+y`
> 2. Press `,` without `CTRL-y` immediately

Thanks bro!
