### ISSUE TITLE
Replaces $ for 1's

### ISSUE THREAD

**Issue by oscarcardoso** [mattn/emmet-vim#196]
I was running emmet in a IMG tag with a few calls to php. When enclosing the img tag and trying to create an anchor tag outside the img, all the $ are replaced by 1's.

**Comment by zonika** [comment]
Not sure why this is being ignored but I'm having this issue too. My use case is when referring to some angular specific variables/functions (which are prepended with $, $close(), for example) in html attributes, then expanding them and having the $ replaced with 1. I think this is because emmet thinks I want to use the $ as a counter, when I really just want it to stay a $. An example:

```
div[ng-click="$close()"]

expands into...

<div ng-click="1close()"></div>
```

Is there a way to override the character Emmet looks for to signify a counter? Thanks!

**Comment by mattn** [comment]
set dollar_expr off.

```vim
  let g:user_emmet_settings = {
  \  'php' : {
  \    'extends' : 'html',
  \    'filters' : 'html,c',
  \    'dollar_expr': 0,
  \  },
  \}
```
