### ISSUE TITLE
"lorem" does not expand as text

### ISSUE THREAD

**Issue by guywald1** [mattn/emmet-vim#344]
`a(lorem3)`

expands to

`< href=""></a>
Lorem ipsum dolor.`

as opposed to:

`<a href="">Lorem ipsum dolor</a>`

**Comment by gilmrjc** [comment]
That is correct, to get the text inside you can use a>lorem3

**Comment by NHungate** [comment]
Expansions made inside of parentheses will not be nested by default. 

`div(span)`

results in:

```
<div></div>
<span></span>
```

And the same expectation would follow for using the lorem expansion.

@gilmrjc has has the correct solution

Also as a side note, though brackets `{}` are also used for inserting text into a tag, they would lead to a literal insertion of `<a>lorem3</a>` rather than actual lorem ipsum.
