### ISSUE TITLE
It would be great if you could tab through the resulting tags

### ISSUE THREAD

**Issue by wamoyo** [mattn/emmet-vim#353]

**Comment by mattn** [comment]
What do you mean. Please explain.

**Comment by wamoyo** [comment]
In snipmate, which in all fairness is different, there are stop points that you can define. For example:

```
snippet html5
<!doctype html>
<html>
  <head>
    <title>${1:default title}</title>
  </head>
  <body>
    ${2:default content}
  </body>
</html>
```

Those tab stops $1 and $2 are where you go when you press tab. So, you'd type `html5` then hit `tab` and it would expand. Your cursor would be in the title with the default text highlighted. the next time you hit tab, you'd go to the second tab stop with that default text highlighted, if there is any. In emmet there wouldn't be a need for default text. 

It's not a perfect system, but it is quite simple, and you can make a nav bar and fill in it's respective links in mere seconds.

Just a nice to have.

**Comment by dNitro** [comment]
Actually emmet-vim already have this functionality. See [Go to next edit point](https://github.com/mattn/emmet-vim/blob/44906fb16eb276622f1b8dbb3ab3062310a5b34c/doc/emmet.txt#L239-L249) and [Go to previous edit point](https://github.com/mattn/emmet-vim/blob/44906fb16eb276622f1b8dbb3ab3062310a5b34c/doc/emmet.txt#L251-L261) sections in documentation.
So you can go to next edit point with `<C-y>n` and to previous edit point with `<C-y>N` if your user_emmet_leader_key is `<C-y>` ( `let g:user_emmet_leader_key='<C-y>'` );
You just need to map these actions to your desired key, here `<Tab>`. so according to [Key mapping](https://github.com/mattn/emmet-vim/blob/44906fb16eb276622f1b8dbb3ab3062310a5b34c/doc/emmet.txt#L1283-L1284) section of documentation just letting:
```vim
let g:user_emmet_next_key = '<Tab>'
let g:user_emmet_prev_key = '<S-Tab>'
```
But this way you will loose snipmate snippet expansion using `Tab` so you should make your tab a super tab. somthing like the following mapping:
```vim
inoremap <silent> <expr> <Tab> s:superTab()

function! s:superTab()
  if &filetype == 'html' &&
      \ search('></', 'nW') > 0 ||
      \ search('""', 'nW') > 0 ||
      \ search ('<[^<> /]*>\n^\s*$', 'nW') > 0
      return "\<C-R>=emmet#moveNextPrev(0)\<CR>"
  else
      return "\<C-R>=snipMate#TriggerSnippet()\<CR>"
  endif
endfunction
```
here when we hit tab, vim checks whether if the filetype is `html` and after cursor position there is `></` or `""` or an empty line between open and closing tag ( these are places where emmet will jump) then does *emmet jump* otherwise snipmate expansion and jump if any and if not just inserts a regular `Tab` charachter.

Of course this is a rude implementation specially in checking places where emmet can jump so it would be nice to have functions like for example **emmet#isExpandable** or **emmet#nextExists** to check that conditions and fine tune tab functionality.

**Comment by wamoyo** [comment]
Ah, you rock! Sorry, my mistake.
